#!/bin/bash
# Выводит процедуру beat4tmux в окошко tmux
# $1 DB ID

# safe bash
set -o errexit -o noclobber -o nounset -o pipefail

readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
. "${root_dir}/load_config.bash"
. "${lib_dir}/heartbeat.bash"

# $1 DB ID
db=$1

while true;
do
	heartbeat_psql "$(slaves4URL $db)" 'beat4tmux' 'any' "call beat4tmux('${db_suffix[$db]}')" \
		|| true
	sleep 1
done
