#!/bin/bash
# $@ список кластеров, которые надо протестировать, если пустой, то все
# safe bash
set -o errexit -o noclobber -o nounset -o pipefail -o xtrace

readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
. "${root_dir}/load_config.bash"

. "${lib_dir}/power_on.bash"
. "${lib_dir}/power_off.bash"
. "${lib_dir}/rollback.bash"
. "${lib_dir}/count_words.bash"
. "${lib_dir}/tmux.bash"
. "${lib_dir}/clusters2hosts.bash"

readonly clusters="${*:-${!cluster_dbs[*]}}"
declare -a pane_test
declare -i n=$(count_words $clusters)
tmux_init
for c in $clusters
do
	pane_test[$c]="$(tmux display-message -p '#{pane_id}')"
	if [ $n -gt 1 ]
	then
		tmux split-window -h -p $((100-100/n)) ''
		let n-=1
	fi
done; unset c
for c in $clusters
do
	tmux respawn-pane -t "${pane_test[$c]}" -k "'${test_dir}/failure1' ${c}"
done; unset c

rollback 'setup' ${cluster_vms[${Group0}]}
power_on ${cluster_vms[${Group0}]}

tmux_attach

# Finish, cleanup
power_off $(clusters2hosts ${Group0} ${clusters})

exit 0
