#!/bin/bash
# Выводит процедуру heart4tmux в окошко tmux
# $1 DB ID

# safe bash
set -o errexit -o noclobber -o nounset -o pipefail

readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
. "${root_dir}/load_config.bash"
. "${lib_dir}/heartbeat.bash"

# $1 DB ID
db=$1

while true;
do
	heartbeat_psql "${float_name[$db]}:${db_port[$db]}" 'heart4tmux' 'read-write' "call heart4tmux('${db_suffix[$db]}')" \
		|| true
	sleep 1
done
