#!/bin/bash
# Вспомогательный скрипт к random_failure, слушает названия виртуалок с которых можно мониторить
# и запускает программы мониторинга в tmux pane.
# $1 pane_mon
# $2 pane_top
# safe bash
set -o errexit -o noclobber -o nounset -o pipefail

readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
. "${root_dir}/load_config.bash"
. "${lib_dir}/vm_ssh.bash"

pane_mon="$1"
pane_top="$2"
h=''
while read
do
	if [ "$h" = "$REPLY" ]
	then
		continue
	fi
	h="$REPLY"
	echo -ne "\n${vm_name[$h]}"
	# copy/pasted from lib/vm_ssh.bash
	tmux respawn-pane -t "${pane_mon}" -k "'${lib_dir}/vm_ssh' ${h} -t 'crm_mon -rDfAi 0.1'"
	tmux respawn-pane -t "${pane_top}" -k "'${lib_dir}/vm_ssh' ${h} -t 'HTOPRC=~/.config/htop/tuchanka.htoprc htop'"
done;unset h
