#!/bin/bash
# safe bash
set -o errexit -o noclobber -o nounset -o pipefail -o xtrace

readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
. "${root_dir}/load_config.bash"

. "${lib_dir}/rollback.bash"
. "${lib_dir}/tick.bash"
. "${lib_dir}/power_on.bash"
. "${lib_dir}/tmux.bash"

tick_destination="$(tmux split-window -P -F '#{pane_id}' -h -b -d -l 15 '')"

rollback 'setup'
while true
do
	tick+
	power_on
	for vm in "${vm_name[@]}"
	do
		VBoxManage controlvm "${vm}" reset
	done
	sleep 1
done

exit 0
