#!/bin/bash
# Проверка стабильности VirtualBox при reset на несколько виртуалок.

# safe bash
set -o errexit -o noclobber -o nounset -o pipefail -o xtrace

# get config
readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
. "${root_dir}/load_config.bash"

. "${lib_dir}/tmux.bash"
. "${lib_dir}/power_off.bash"

tmux_init

tmux respawn-pane -k "${test_dir}/reset1"

tmux_attach

# Finish, cleanup
power_off

exit 0
