#!/bin/bash
# Проверка на стабильность при массовом откате
# safe bash
set -o errexit -o noclobber -o nounset -o pipefail -o xtrace

# get config
readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
. "${root_dir}/load_config.bash"

. "${lib_dir}/tmux.bash"
. "${lib_dir}/cleanup.bash"

trap cleanup EXIT
tmux_init
tmux respawn-pane -k "${test_dir}/rollback1"
tmux_attach
exit 0
# cleanup by trap
