#!/bin/bash
# тестирование "наработкой на отказ"  конфигурационных скриптов
# install не тестирую, чтобы не создавать большой трафик

# safe bash
set -o errexit -o noclobber -o nounset -o pipefail -o xtrace

# get config
readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
. "${root_dir}/load_config.bash"

. "${lib_dir}/tmux.bash"

# Виртуалки будут остановлены вложенным скриптом
# Поэтому только tmux_cleanup для закрытия tmux
trap tmux_cleanup EXIT
tmux_init
tmux respawn-pane -k "${test_dir}/setup1"
tmux_attach
exit 0
# tmux_cleanup by trap
