#!/bin/bash
# safe bash
set -o errexit -o noclobber -o nounset -o pipefail -o xtrace

# get config
readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
. "${root_dir}/load_config.bash"

. "${lib_dir}/tick.bash"
. "${lib_dir}/tmux.bash"

tick_destination="$(tmux split-window -P -F '#{pane_id}' -h -b -d -l 15 '')"

while true
do
	tick+
	"${setup_dir}/setup"
done

exit 0
