#!/bin/bash
# safe bash
set -o errexit -o noclobber -o nounset -o pipefail

# тестирование "наработкой на отказ"  конфигурационных скриптов
# install не тестирую, чтобы не создавать большой трафик
# get config
readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
. "${root_dir}/load_config.bash"

i=0
echo "i=$i $(date +'%FT%T')" |tee 'test.log'
while true
do
	"${setup_dir}/setup"
	let i=$i+1
	echo "i=$i $(date +'%FT%T')" |tee -a 'test.log'
done
