#!/bin/bash
# Тест на стабильность VirtualBox на включение/выключение
# safe bash
set -o errexit -o noclobber -o nounset -o pipefail

readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
. "${root_dir}/load_config.bash"

. "${lib_dir}/power_on.bash"
. "${lib_dir}/shut_down.bash"
. "${lib_dir}/tick.bash"

while true
do
	tick+
	power_on
	shut_down
done
