#!/bin/bash
# safe bash
set -o errexit -o noclobber -o nounset -o pipefail

readonly script_dir="$(dirname "${BASH_SOURCE[0]}")/../script"

. "${script_dir}/load_config.bash"
. "${script_dir}/start_vms.bash"
. "${script_dir}/soft_off.bash"
i=0
echo "i=$i $(date +'%FT%T')" |tee 'test.log'
while true
do
	start_vms
	soft_off
	let i=$i+1
	echo "i=$i $(date +'%FT%T')" |tee -a 'test.log'
done
