#!/bin/bash
# safe bash
set -o errexit -o noclobber -o nounset -o pipefail -o xtrace

# тестирование "наработкой на отказ" start --all/stop --all
readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
. "${root_dir}/load_config.bash"

. "${lib_dir}/vm_ssh.bash"
. "${lib_dir}/rollback.bash"
. "${lib_dir}/power_on.bash"
. "${lib_dir}/shut_down.bash"
. "${lib_dir}/tick.bash"
. "${lib_dir}/wait_healthy.bash"

rollback 'setup'
while true
do
	tick+
	power_on
	for i in "${!cluster_name[@]}"
	do
		vm_ssh "${vm_name[$i]}" "pcs --debug cluster start --all --wait"
	done;unset i
	for i in "${!cluster_name[@]}"
	do
		wait_healthy $i
		vm_ssh "${vm_name[$i]}" "pcs --debug cluster stop --all --wait"
	done;unset i
	sleep 5
	shut_down
done
