#!/bin/bash
# Copyright Ⓒ 2020 "Sberbank Real Estate Center" Limited Liability Company.
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the Software
# is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

# safe bash
set -o errexit -o noclobber -o nounset -o pipefail -o xtrace

readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
. "${root_dir}/load_config.bash"

. "${lib_dir}/vm_ssh.bash"
. "${lib_dir}/rollback.bash"
. "${lib_dir}/power_on.bash"
. "${lib_dir}/shut_down.bash"
. "${lib_dir}/tick.bash"
. "${lib_dir}/wait_healthy.bash"
. "${lib_dir}/first_vm.bash"
. "${lib_dir}/tmux.bash"
. "${lib_dir}/wait_qdevice.bash"

# Индекс кластера
# не ставлю readonly из-за странного конфликта с декларированием local переменных в функциях
c="$1"

# Setup tmux panes
readonly pane_test="${TMUX_PANE}"
# for function tick
readonly tick_destination="$(tmux split-window -t "${pane_test}" -P -F '#{pane_id}' -v -b -l 10 '')"

# Start VM
tick "Rollback tuchanka${c}"
rollback 'setup' ${cluster_vms[$c]}
tick "Boot tuchanka${c}"
power_on ${cluster_vms[$c]}
tick "Wait for quorum device"
wait_qdevice

while true
do
	tick+ "Boot tuchanka${c}"
	power_on ${cluster_vms[$c]}
	tick "Start tuchanka${c}"
	vm_ssh $(first_vm $c) "pcs --debug cluster start --all --wait"
	tick "Is healthy? tuchanka${c}"
	wait_healthy $c
	tick "Stop tuchanka${c}"
	vm_ssh "$(first_vm $c)" "pcs --debug cluster stop --all --wait"
	sleep 5
	tick "Shutdown tuchanka${c}"
	shut_down ${cluster_vms[$c]}
done;
