#!/bin/bash
# safe bash
set -o errexit -o noclobber -o nounset -o pipefail -o xtrace

# тестирование "наработкой на отказ" start --all/stop --all
readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
. "${root_dir}/load_config.bash"

. "${lib_dir}/vm_ssh.bash"
. "${lib_dir}/rollback.bash"
. "${lib_dir}/start_vms.bash"
. "${lib_dir}/soft_off.bash"

i=0
echo "i=$i $(date +'%FT%T')" |tee 'test.log'
while true
do
	# Если не откатывать, то со временем переполняются винчестеры :)
	rollback 'setup'
	start_vms
	for k in "${!krogan_cluster[@]}"
	do
		# Нужен любой hostname из кластера для ssh доступа
		h="${vm_hostname[${db_master[$k]}]}"
		vm_ssh "$h" "pcs --debug cluster start --all --wait"
	done
	for h in "${float_hostname[@]}"
	do
		echo "Waiting for ping ${h}"
		while ! ping -q -c 1 "${h}"
		do
			sleep 5
		done
	done
	for k in "${!krogan_cluster[@]}"
	do
		# Нужен любой hostname из кластера для ssh доступа
		h="${vm_hostname[${db_master[$k]}]}"
		vm_ssh "$h" "pcs --debug cluster stop --all --wait"
	done
	sleep 5
	soft_off
	let i=$i+1
	echo "i=$i $(date +'%FT%T')" |tee -a 'test.log'
done
