#!/bin/bash
# тестирование "наработкой на отказ" start --all/stop --all
# safe bash
set -o errexit -o noclobber -o nounset -o pipefail -o xtrace

readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
. "${root_dir}/load_config.bash"

. "${lib_dir}/vm_ssh.bash"
. "${lib_dir}/rollback.bash"
. "${lib_dir}/power_on.bash"
. "${lib_dir}/shut_down.bash"
. "${lib_dir}/tick.bash"
. "${lib_dir}/wait_healthy.bash"
. "${lib_dir}/first_vm.bash"

rollback 'setup'
while true
do
	tick+
	power_on
	for c in "${!cluster_dbs[@]}"
	do
		vm_ssh "$(first_vm $c)" "pcs --debug cluster start --all --wait"
	done;unset c
	for c in "${!cluster_dbs[@]}"
	do
		wait_healthy $c
		vm_ssh "$(first_vm $c)" "pcs --debug cluster stop --all --wait"
	done;unset c
	sleep 5
	shut_down
done
