#!/bin/sh
while true;
do
	psql \
		--dbname='postgresql://heartbeat:ChangeMe@krogan2s1/heartbeat?connect_timeout=2&application_name=beat2&keepalives=1&keepalives_idle=1&keepalives_interval=1&keepalives_count=1&target_session_attrs=any' \
		--command="call beat('2')" \
		--no-align --quiet --tuples-only --no-psqlrc
	sleep 1
done
