#!/bin/sh
while true;
do
	psql \
		--dbname='postgresql://heartbeat:ChangeMe@krogan1a:5433/heartbeat?connect_timeout=2&application_name=heart1a&keepalives=1&keepalives_idle=1&keepalives_interval=1&keepalives_count=1&target_session_attrs=read-write' \
		--command="call heart4tmux('1a')" \
		--no-align --quiet --tuples-only --no-psqlrc
	sleep 1
done
