#!/bin/sh
while true;
do
	psql \
		--dbname='postgresql://heartbeat:ChangeMe@krogan1b:5434/heartbeat?connect_timeout=2&application_name=heart1b&keepalives=1&keepalives_idle=1&keepalives_interval=1&keepalives_count=1&target_session_attrs=read-write' \
		--command="call heart('1b')" \
		--no-align --quiet --tuples-only --no-psqlrc
	sleep 1
done
