#!/bin/bash
# Copyright Ⓒ 2020 "Sberbank Real Estate Center" Limited Liability Company.
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the Software
# is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

# Софтверный shutdown кластеров
# $@ номера кластеров, если пустой то все (включая Group0)

# safe bash
set -o errexit -o noclobber -o nounset -o pipefail

# get config
readonly root_dir="$(dirname "${BASH_SOURCE[0]}")"
. "${root_dir}/load_config.bash"
. "${lib_dir}/shut_down.bash"
. "${lib_dir}/clusters2hosts.bash"
. "${lib_dir}/is_vm_running.bash"

# $@ номера кластеров, если пустой то все (включая Group0)
readonly clusters="${*:-${!cluster_vms[*]}}"

# Список виртуалок, которые онлайн
hosts=''
for h in $(clusters2hosts ${clusters})
do
	is=$(is_vm_running $h)
	if $is
	then
		hosts+=" ${h}"
	fi
done; unset h is
# remove leading ' '
hosts="${hosts#' '}"

if [ -n "${hosts}" ]
then
	shut_down ${hosts}
fi
unset hosts

exit 0
