#!/bin/bash
# safe bash
set -o errexit -o noclobber -o nounset -o pipefail -o xtrace

# get config
readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/"
. "${root_dir}/load_config.bash"
. "${lib_dir}/vm_ssh.bash"
. "${lib_dir}/tmux.bash"

tmux_init

declare -i n=${#vm_name[@]} i=0
for h in "${!vm_name[@]}"
do
	tmux respawn-pane -k "'${lib_dir}/vm_ssh' $h -t"
	if [ $n -gt 1 ]
	then
		tmux split-window -h -p $((100-100/n))
		let n-=1
	fi
	let i+=1
done; unset h n i
tmux select-layout tiled

tmux_attach
