#!/bin/bash
# Copyright Ⓒ 2020 "Sberbank Real Estate Center" Limited Liability Company.
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the Software
# is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

# $@ номера кластеров, если пустой то все (включая Group0)
# Создает одновременный ssh ко всем указанным кластерам.
# Для того чтобы одновременно печатать во всех терминалках
# нужно в tmux задать:
# (C-b :) set-option synchronize-panes on
# safe bash
set -o errexit -o noclobber -o nounset -o pipefail -o xtrace

# get config
readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/"
. "${root_dir}/load_config.bash"
. "${lib_dir}/vm_ssh.bash"
. "${lib_dir}/tmux.bash"
. "${lib_dir}/clusters2hosts.bash"
. "${lib_dir}/count_words.bash"

# $@ номера кластеров, если пустой то все (включая Group0)
readonly clusters="${*:-${!cluster_vms[*]}}"
readonly hosts=$(clusters2hosts ${clusters})

trap tmux_cleanup EXIT
tmux_init

declare -i n=$(count_words ${hosts}) i=0
for h in ${hosts}
do
	tmux respawn-pane -k "'${lib_dir}/vm_ssh' $h -t"
	if [ $n -gt 1 ]
	then
		tmux split-window -h -p $((100-100/n))
		let n-=1
	fi
	let i+=1
done; unset h n i
tmux select-layout tiled

tmux_attach
exit 0
# tmux_cleanup by trap
