#!/bin/bash
# safe bash
set -o errexit -o noclobber -o nounset -o pipefail

# get config
readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/"
. "${root_dir}/load_config.bash"
. "${lib_dir}/vm_ssh.bash"

if ! tmux has-session -t tuchanka_vm_ssh
then
	tmux new-session -d -s tuchanka_vm_ssh -n tuchanka_vm_ssh -x $COLUMNS -y $LINES
	tmux set-option mouse on
	tmux set-option status off
	tmux set-window-option synchronize-panes on
	tmux set-window-option remain-on-exit on

	declare -i n=${#vm_name[@]} i=0
	for h in "${!vm_name[@]}"
	do
		tmux respawn-pane -k "'${lib_dir}/vm_ssh' $h -t"
		if [ $n -gt 1 ]
		then
			tmux split-window -h -p $((100-100/n))
			let n-=1
		fi
		let i+=1
	done; unset h n i
	tmux select-layout tiled
	tmux select-pane -t '0'
fi

tmux attach-session -t tuchanka_vm_ssh
