#!/bin/bash
# Софтверный shutdown кластеров
# $@ номера кластеров, если пустой то все (включая Group0)

# safe bash
set -o errexit -o noclobber -o nounset -o pipefail

# get config
readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
. "${root_dir}/load_config.bash"
. "${lib_dir}/shut_down.bash"
. "${lib_dir}/clusters2hosts.bash"

# $@ номера кластеров, если пустой то все (включая Group0)
readonly clusters="${*:-${!cluster_vms[*]}}"

shut_down $(clusters2hosts ${clusters})
