#!/bin/bash
# simple wrapper for library function shut_down
# $@ go to the function shut_down

# safe bash
set -o errexit -o noclobber -o nounset -o pipefail

# get config
readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
. "${root_dir}/load_config.bash"
. "${lib_dir}/shut_down.bash"

shut_down "$@"
