#!/bin/bash
# safe bash
set -o errexit -o noclobber -o nounset -o pipefail -o xtrace

pcs cluster cib original_cib.xml
cp original_cib.xml configured_cib.xml
pcs -f configured_cib.xml resource create krogan1bDB ocf:heartbeat:pgsqlms bindir=/usr/pgsql-11/bin pgdata=/var/lib/pgsql/krogan1b pgport=5434 recovery_template=/var/lib/pgsql/krogan1b.paf op monitor interval=15 timeout=10 monitor interval=16 role=Master timeout=15 monitor interval=17 role=Slave timeout=10 meta master notify=true resource-stickiness=10
pcs -f configured_cib.xml resource create krogan1bIP ocf:heartbeat:IPaddr2 nic=eth0 cidr_netmask=24 ip=192.168.89.102
pcs -f configured_cib.xml constraint location krogan1bDB-master rule role=master score=100 '#uname' eq string tuchanka1b and master-krogan1bDB ne integer 1001
pcs -f configured_cib.xml constraint colocation add krogan1bIP with master krogan1bDB-master INFINITY
pcs -f configured_cib.xml constraint order promote krogan1bDB-master then start krogan1bIP symmetrical=false
pcs -f configured_cib.xml constraint order demote krogan1bDB-master then stop krogan1bIP symmetrical=false kind=Optional
pcs cluster cib-push configured_cib.xml --wait diff-against=original_cib.xml
