#!/bin/bash
# safe bash
set -o errexit -o noclobber -o nounset -o pipefail -o xtrace

pcs cluster cib original_cib.xml
cp original_cib.xml configured_cib.xml
pcs -f configured_cib.xml resource create krogan2DB ocf:heartbeat:pgsqlms bindir=/usr/pgsql-11/bin pgdata=/var/lib/pgsql/krogan2 recovery_template=/var/lib/pgsql/krogan2.paf meta master notify=true resource-stickiness=10
pcs -f configured_cib.xml resource create krogan2IP ocf:heartbeat:IPaddr2 nic=eth0 cidr_netmask=24 ip=192.168.89.105
pcs -f configured_cib.xml resource create krogan2sIP ocf:heartbeat:IPaddr2 nic=eth0 cidr_netmask=24 ip=192.168.89.106 unique_clone_address=true clone interleave=true globally-unique=true resource-stickiness=0 clone-max=3
pcs -f configured_cib.xml constraint colocation add krogan2IP with master krogan2DB-master INFINITY
pcs -f configured_cib.xml constraint order promote krogan2DB-master then start krogan2IP symmetrical=false
pcs -f configured_cib.xml constraint order demote krogan2DB-master then stop krogan2IP symmetrical=false kind=Optional
pcs -f configured_cib.xml constraint location krogan2sIP-clone rule score=-INFINITY master-krogan2DB lt integer 0
pcs -f configured_cib.xml constraint colocation add krogan2sIP-clone with slave krogan2DB-master INFINITY
pcs -f configured_cib.xml constraint order start krogan2DB-master then start krogan2sIP-clone
pcs cluster cib-push configured_cib.xml --wait diff-against=original_cib.xml
