#!/bin/bash
# safe bash
set -o errexit -o noclobber -o nounset -o pipefail -o xtrace

pcs cluster cib original_cib.xml
cp original_cib.xml configured_cib.xml
pcs -f configured_cib.xml resource create krogan0bDB ocf:heartbeat:pgsqlms bindir=/usr/pgsql-11/bin pgdata=/var/lib/pgsql/krogan0b pgport=5434 recovery_template=/var/lib/pgsql/krogan0b.paf op monitor interval=15 timeout=10 monitor interval=16 role=Master timeout=15 monitor interval=17 role=Slave timeout=10 meta master notify=true resource-stickiness=10
pcs -f configured_cib.xml resource create krogan0bIP ocf:heartbeat:IPaddr2 nic=eth0 cidr_netmask=24 ip=192.168.89.102
pcs -f configured_cib.xml constraint location krogan0bDB-master rule role=master score=100 '#uname' eq string tuchanka0b and master-krogan0bDB ne integer 1001
pcs -f configured_cib.xml constraint colocation add krogan0bIP with master krogan0bDB-master INFINITY
pcs -f configured_cib.xml constraint order promote krogan0bDB-master then start krogan0bIP symmetrical=false
pcs -f configured_cib.xml constraint order demote krogan0bDB-master then stop krogan0bIP symmetrical=false kind=Optional
pcs cluster cib-push configured_cib.xml --wait diff-against=original_cib.xml
