#!/bin/bash
# safe bash
set -o errexit -o noclobber -o nounset -o pipefail -o xtrace

pcs cluster cib original_cib.xml
cp original_cib.xml configured_cib.xml
pcs -f configured_cib.xml resource create krogan0aDB ocf:heartbeat:pgsqlms bindir=/usr/pgsql-11/bin pgdata=/var/lib/pgsql/krogan0a pgport=5433 recovery_template=/var/lib/pgsql/krogan0a.paf meta master notify=true resource-stickiness=10
pcs -f configured_cib.xml resource create krogan0aIP ocf:heartbeat:IPaddr2 nic=eth0 cidr_netmask=24 ip=192.168.89.101
pcs -f configured_cib.xml constraint location krogan0aDB-master rule role=master score=100 '#uname' eq string tuchanka0a and master-krogan0aDB ne integer 1001
pcs -f configured_cib.xml constraint colocation add krogan0aIP with master krogan0aDB-master INFINITY
pcs -f configured_cib.xml constraint order promote krogan0aDB-master then start krogan0aIP symmetrical=false
pcs -f configured_cib.xml constraint order demote krogan0aDB-master then stop krogan0aIP symmetrical=false kind=Optional
pcs cluster cib-push configured_cib.xml --wait diff-against=original_cib.xml
