#!/bin/bash
# safe bash
set -o errexit -o noclobber -o nounset -o pipefail -o xtrace

# get config
script_dir="$(dirname "${BASH_SOURCE[0]}")"
. "${script_dir}/load_config.bash"
. "${script_dir}/vm_ssh.bash"

if $autoVirtualBox
then
	. "${script_dir}/rollback.bash"
	. "${script_dir}/start_vms.bash"
	. "${script_dir}/snapshot.bash"
fi

if $autoVirtualBox
then
	rollback 'create_vms'
	start_vms
else
	echo 'При автоматической установке здесь происходит откат к snapshot, который был создан после создания виртуалок и инсталяции линукса.'
fi

for h in "${vm_hostname[@]}"
do
	echo "Install soft to $h"
	vm_ssh "$h" 'localectl set-locale LANG=ru_RU.UTF-8 LC_MESSAGES=en_US.UTF-8 LANGUAGE=en'
#	unstable #	vm_ssh "$h" 'yum --assumeyes install deltarpm'
	vm_ssh "$h" 'yum --assumeyes update'
	# для htop нужен epel
	vm_ssh "$h" 'yum --assumeyes install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm'
	vm_ssh "$h" 'yum --assumeyes install mc vim nmap mlocate htop pcs gpm ntp screen bind-utils'
	vm_ssh "$h" 'yum --assumeyes erase chrony'
	vm_ssh "$h" 'yum --assumeyes install http://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm'
	vm_ssh "$h" 'yum --assumeyes install zabbix-agent'
	if [ "$h" = "${vm_hostname[${Witness}]}" ]
	then
		vm_ssh "$h" 'yum --assumeyes install corosync-qnetd'
	else
		vm_ssh "$h" "yum --assumeyes install https://download.postgresql.org/pub/repos/yum/${postgresql_version}/redhat/rhel-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
		vm_ssh "$h" "yum --assumeyes install postgresql${postgresql_version} postgresql${postgresql_version}-server postgresql${postgresql_version}-contrib pgcenter resource-agents-paf corosync-qdevice sbd awscli"
	fi
done

if $autoVirtualBox
then
	snapshot 'install_soft' 'The snapshot was taken at the end of the "install_soft" script.'
else
	echo 'При автоматической установке здесь сохраняется snapshot с доустановленными пакетами.'
	echo 'Перед следующим этапом "configure" убедитесь, что у сетевого интерфейса, который будет использоваться с floating ip имя eth0.'
fi

exit 0
