#!/bin/bash
# safe bash
set -o errexit -o noclobber -o nounset -o pipefail

# тестирование "наработкой на отказ"  конфигурационных скриптов
# install_soft не тестирую, чтобы не создавать большой трафик
# get config
readonly script_dir="$(dirname "${BASH_SOURCE[0]}")"
i=0
echo "i=$i $(date +'%FT%T')" |tee 'test.log'
while true
do
	"${script_dir}/configure"
	"${script_dir}/heartbeat"
	let i=$i+1
	echo "i=$i $(date +'%FT%T')" |tee -a 'test.log'
done
