#!/bin/bash
# safe bash
set -o errexit -o noclobber -o nounset -o pipefail

# get config
readonly script_dir="$(dirname "${BASH_SOURCE[0]}")"

"${script_dir}/destroy_vms"
time "${script_dir}/create_vms" "$@"
time "${script_dir}/install_soft"
time "${script_dir}/configure"
time "${script_dir}/heartbeat"

exit 0
