#!/bin/bash
# safe bash
set -o errexit -o noclobber -o nounset -o pipefail

# get config
readonly script_dir="$(dirname "${BASH_SOURCE[0]}")"
. "${script_dir}/load_config.bash"

if ! $autoVirtualBox
then
	echo 'Этот скрипт работает только со snapshot сделанными в VirtualBox.'
	exit 1
fi

. "${script_dir}/rollback.bash"
rollback 'install_soft'
exit 0
