#!/bin/bash
# safe bash
set -o errexit -o noclobber -o nounset -o pipefail -o xtrace

# get config
readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
. "${root_dir}/load_config.bash"

if $autoVirtualBox
then
	. "${lib_dir}/destroy_vm.bash"
	destroy_vm
else
	echo 'При автоматической установке здесь удаляются виртуалки и интерфейс админского компьютера во внутренней подсетке.'
fi

echo 'Удаляю автоматический сгенерённые конфигурационные файлы'
[ -e "${ssh_known_hosts}" ] && rm "${ssh_known_hosts}"
[ -e "${ssh_config}" ] && rm "${ssh_config}"
[ -e "${etc_hosts}" ] && rm "${etc_hosts}"

exit 0
