#!/bin/bash
# safe bash
set -o errexit -o noclobber -o nounset -o pipefail

# get config
readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
. "${root_dir}/load_config.bash"
. "${lib_dir}/is_grep.bash"

if $autoVirtualBox
then
	. "${lib_dir}/power_off.bash"

	power_off
	for vm in "${!vm_name[@]}"
	do
		is=$(VBoxManage list vms | is_grep "^\"${vm_name[$vm]}\" ")
		if $is
		then
			echo "destroy ${vm_name[$vm]}"
			VBoxManage unregistervm "${vm_name[$vm]}" --delete
		fi
	done;unset vm is

	# get name for hostonlyif
	vboxnet_if="$(VBoxManage list hostonlyifs|
		tr '\n' '§'|sed -nE "/^.*Name:[[:space:]]+([[:alnum:]]+)§GUID:[^§]+§DHCP:[^§]+§IPAddress:[[:space:]]+${vboxnet_hostip//./\.}§.*$/ s//\1/p")"
	if [ -n "${vboxnet_if}" ]
	then
		VBoxManage hostonlyif remove "${vboxnet_if}"
		echo "removed vboxnet_if=>${vboxnet_if}"
	fi
	unset -v vboxnet_if
else
	echo 'При автоматической установке здесь удаляются виртуалки и интерфейс админского компьютера во внутренней подсетке.'
fi

echo 'Удаляю автоматический сгенерённые конфигурационные файлы'
[ -e "${ssh_known_hosts}" ] && rm "${ssh_known_hosts}"
[ -e "${ssh_config}" ] && rm "${ssh_config}"
[ -e "${etc_hosts}" ] && rm "${etc_hosts}"

exit 0
