#!/bin/bash
# safe bash
set -o errexit -o noclobber -o nounset -o pipefail -o xtrace

# get config
readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
. "${root_dir}/load_config.bash"
. "${lib_dir}/vm_ssh.bash"

# create_vms
if $autoVirtualBox
then
	# check command line arguments
	if [ $# -ne 2 ]
	then
		echo -e "Usage:\n\t $0 <redhat_installation_image.iso> <ssh_public_key_file>" 1>&2
		exit 1
	fi
	dvd_iso="$1"
	echo "Check installation image \"${dvd_iso}\""
	eval $(VBoxManage unattended detect --iso "${dvd_iso}" --machine-readable)
	if [ "$OSTypeId" = 'RedHat_64' -a "$OSVersion" = '7' ]
	then
		echo "The installation image \"${dvd_iso}\" is Ok"
	else
		echo "Error: The installation image must be RedHat 7 64bit or so like (CentOS, for instance)" 1>&2
		exit 2
	fi
	ssh_public_key="$2"
	echo "Check ssh public key \"${ssh_public_key}\""
	if [ -r "${ssh_public_key}" ]
	then
		ssh_fingerprint="$(ssh-keygen -l -f "${ssh_public_key}" | cut -d ' ' -f 2)"
	else
		echo "Error: The ssh public key file is not readable" 1>&2
		exit 3
	fi
fi

if $autoVirtualBox
then
	. "${lib_dir}/snapshot.bash"
	. "${lib_dir}/vboxvm_dir.bash"
fi

# generate config files for other scripts
# create ssh_config (with check of clean install)
if [ -e "${ssh_config}" ]
then
	echo "Error: ssh_config already exists, install is not clean" 1>&2
	exit 4
fi
# keep fingerprint of ssh inside ssh_config comments
echo "${vm_ssh_add_key_prefix}${ssh_fingerprint}" >"${ssh_config}"
unset ssh_fingerprint
# add key to the ssh-agent, if abscent
vm_ssh_add
ssh_hosts=''
for i in "${!vm_name[@]}"
do
	echo -e "Host ${vm_name[$i]}\n\tHostName ${vm_ip[$i]}"
	ssh_hosts="${ssh_hosts} ${vm_name[$i]}"
done >>"${ssh_config}";unset i
cat <<EOF >>"${ssh_config}"
Host ${ssh_hosts}
	ForwardAgent yes
	ForwardX11 no
	AddKeysToAgent yes
	AddressFamily inet
	BatchMode yes
	BindAddress ${vboxnet_hostip}
	CanonicalizeHostname no
	CheckHostIP yes
	Compression no
	HashKnownHosts no
	LogLevel ERROR
	RequestTTY no
	StrictHostKeyChecking yes
	User root
	TCPKeepAlive yes
	ServerAliveInterval 5
EOF
unset ssh_hosts
# generate etc_hosts file
for i in "${!vm_name[@]}"
do
	echo -e "${vm_ip[$i]}\t${vm_name[$i]} ${vm_name[$i]}.tuchanka"
done > "${etc_hosts}";unset i
for i in "${!float_ip[@]}"
do
	echo -e "${float_ip[$i]}\t${float_name[$i]} ${float_name[$i]}.tuchanka"
done >> "${etc_hosts}";unset i
echo -e "${vboxnet_hostip}\tvirtualbox virtualbox.tuchanka" >> "${etc_hosts}"

if $autoVirtualBox
then
	# Подсетка кластера
	echo 'Create a network interface for the host'
	# get name for hostonlyif, if exists
	vboxnet_if="$(VBoxManage list hostonlyifs|
		tr '\n' '§'|sed -nE "/^.*Name:[[:space:]]+([[:alnum:]]+)§GUID:[^§]+§DHCP:[^§]+§IPAddress:[[:space:]]+${vboxnet_hostip//./\.}§.*$/ s//\1/p")"
	if [ -z "${vboxnet_if}" ]
	then
		# Создаю интерфейс для hostonly сети и запоминаю имя:
		vboxnet_if="$(VBoxManage hostonlyif create |
			sed -E "s/Interface '(vboxnet[0-9]+)' was successfully created/\1/")"
		# Назначаю IP хосту
		VBoxManage hostonlyif ipconfig "${vboxnet_if}" --ip "${vboxnet_hostip}"
		echo "created vboxnet_if=>${vboxnet_if}"
	else
		echo "Error: vboxnet_if=>${vboxnet_if} already exists" 1>&2
		exit 5
	fi

	# Виртуалки
	for i in "${!vm_name[@]}"
	do
		h="${vm_name[$i]}"
		echo "Create ${h}"
		VBoxManage createvm --name "$h" --groups "${vm_group[$i]}" --ostype RedHat_64 --register
		VBoxManage modifyvm "${h}" --description "${vm_desc[$i]}" --memory $RAM_MiB --vram=$VRAM_MiB --boot1 dvd --boot2 disk --boot3 none --boot4 none --rtcuseutc on --graphicscontroller vboxsvga --firmware bios --defaultfrontend headless --nic1 hostonly --nictype1 virtio --hostonlyadapter1 "${vboxnet_if}" --nic2 nat --nictype2 virtio --mouse usb --keyboard usb --audio none --cpus 2 --iconfile "${root_dir}/images/krogan.png"
		# get host dir
		vboxvm_vdi="$(vboxvm_dir "${h}")/${h}.vdi"
		VBoxManage storagectl "$h" --name 'DiskController' --add sas --hostiocache off --bootable on
		VBoxManage createmedium disk --filename "${vboxvm_vdi}" --size $HDD_MiB
		VBoxManage storageattach "$h" --storagectl 'DiskController' --type hdd --port 0 --device 0 --medium "${vboxvm_vdi}"
		VBoxManage storageattach "$h" --storagectl 'DiskController' --type dvddrive --port 1 --device 0 --medium "${dvd_iso}"
		VBoxManage unattended install "$h" --iso="${dvd_iso}" --full-user-name="${vm_ip[$i]}" --locale='ru_RU' --time-zone="${time_zone}" --hostname="${h}.tuchanka" --package-selection-adjustment='minimal' --script-template="${setup_dir}/redhat7.kickstart" --post-install-command="mkdir -m 700 \"\${MY_TARGET}/root/.ssh\" && echo '$(cat "${ssh_public_key}")' >>\"\${MY_TARGET}/root/.ssh/authorized_keys\"" --start-vm='headless' --extra-install-kernel-parameters='net.ifnames=0 biosdevname=0 ks=cdrom:/ks.cfg'
		echo "Created ${h}"
	done;unset i h
else
	echo 'При автоматической установке создается интерфейс админского компьютера во внутренней подсетке кластера.'
	echo 'Создаются виртуалки, на них устанавливается CentOS с предварительной настройкой в инсталляторе.'
	echo 'И публичный ключ сисадмина записывается пользователю root.'
	echo 'А сейчас ручной режим и поэтому все эти действия необходимо выполнить вручную.'
	echo 'Дальнейшее выполнение скрипта ожидает, что на серверах кластера уже запущен ssh.'
fi

# Жду завершение установки, записываю публичный ключ хоста, выключаю
declare ssh_key
for i in "${!vm_name[@]}"
do
	echo "Waiting for ssh on ${vm_name[$i]}"
	# ssh-keyscan иногда возвращает при ошибках код отличный от 0,
	# иногда нет. Приходится извращаться.
	ssh_key="$(ssh-keyscan -t ssh-ed25519 "${vm_ip[$i]}" 2>/dev/null || true)"
	until [ -n "${ssh_key}" ]
	do
		sleep 5
		ssh_key="$(ssh-keyscan -t ssh-ed25519 "${vm_ip[$i]}" 2>/dev/null || true)"
	done
	echo "${ssh_key}" >>"${ssh_known_hosts}"
	# kdump отключен в kickstart файле, выключаю сервис, чтобы systemctl is-system-runnig корректно работал
	vm_ssh "${vm_name[$i]}" 'systemctl disable kdump.service --quiet'
done;unset i
unset -v ssh_key

#install_soft
for h in "${vm_name[@]}"
do
	echo "Install soft to $h"
	vm_ssh "$h" 'localectl set-locale LANG=ru_RU.UTF-8 LC_MESSAGES=en_US.UTF-8 LANGUAGE=en'
	vm_ssh "$h" 'yum --assumeyes install deltarpm'
	vm_ssh "$h" 'yum --assumeyes update'
	# для htop нужен epel
	vm_ssh "$h" 'yum --assumeyes install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm'
	vm_ssh "$h" 'yum --assumeyes install mc vim nmap mlocate htop pcs gpm ntp screen tmux bind-utils iotop sysbench stress-ng wget'
	vm_ssh "$h" 'yum --assumeyes erase chrony'
	vm_ssh "$h" 'yum --assumeyes install http://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm'
	vm_ssh "$h" 'yum --assumeyes install zabbix-agent'
	if [ "$h" = "${vm_name[${Witness}]}" ]
	then
		vm_ssh "$h" 'yum --assumeyes install corosync-qnetd'
	else
		vm_ssh "$h" "yum --assumeyes install https://download.postgresql.org/pub/repos/yum/${postgresql_version}/redhat/rhel-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
		vm_ssh "$h" "yum --assumeyes install postgresql${postgresql_version} postgresql${postgresql_version}-server postgresql${postgresql_version}-contrib pgcenter resource-agents-paf corosync-qdevice sbd awscli"
	fi
done;unset h

if $autoVirtualBox
then
	snapshot 'install' 'The snapshot was taken at the end of the "install" script.'
else
	echo 'При автоматической установке здесь сохраняется snapshot с установленными пакетами.'
	echo 'Перед следующим этапом "setup" убедитесь, что у сетевого интерфейса, который будет использоваться с floating ip имя eth0.'
fi

exit 0
