#!/bin/bash
# safe bash
set -o errexit -o noclobber -o nounset -o pipefail -o xtrace

# get config
readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
. "${root_dir}/load_config.bash"

. "${lib_dir}/vm_ssh.bash"
. "${lib_dir}/tmux.bash"
if $autoVirtualBox
then
	. "${lib_dir}/delete_snapshot.bash"
	. "${lib_dir}/rollback.bash"
fi

if $autoVirtualBox
then
	rollback 'create'
	# Наличине скриншота setup будет маркером, что install1 скрипт отработал нормально.
	delete_snapshot 'install'
else
	echo 'При автоматической установке здесь происходит откат к snapshot, который был создан после создания виртуалок.'
	read -p 'press enter'
fi

tmux_init
declare -i n=${#vm_name[@]} i=0
for h in "${!vm_name[@]}"
do
	tmux respawn-pane -k "sleep $i && '${setup_dir}/install1' $h"
	if [ $n -gt 1 ]
	then
		tmux split-window -h -p $((100-100/n))
		let n-=1
	fi
	let i+=1
done; unset h n i
tmux select-layout tiled
tmux_attach

# Наличине скриншота install будет маркером, что распараллелеиная установка пакетов отработала нормально
exec "${setup_dir}/setup"
