#!/bin/bash
# Copyright Ⓒ 2020 "Sberbank Real Estate Center" Limited Liability Company.
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the Software
# is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

# safe bash
set -o errexit -o noclobber -o nounset -o pipefail -o xtrace

# get config
readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
. "${root_dir}/load_config.bash"

. "${lib_dir}/vm_ssh.bash"
. "${lib_dir}/tmux.bash"
. "${lib_dir}/cleanup.bash"
. "${lib_dir}/delete_snapshot.bash"
. "${lib_dir}/rollback.bash"

trap cleanup EXIT
rollback 'create'
# Наличине скриншота setup будет маркером, что install1 скрипт отработал нормально.
delete_snapshot 'install'

tmux_init
declare -i n=${#vm_name[@]} i=0
for h in "${!vm_name[@]}"
do
	tmux respawn-pane -k "sleep $i && '${setup_dir}/install1' $h"
	if [ $n -gt 1 ]
	then
		tmux split-window -h -p $((100-100/n))
		let n-=1
	fi
	let i+=1
done; unset h n i
tmux select-layout tiled
tmux_attach
# Наличине скриншота install будет маркером, что распараллелеиная установка пакетов отработала нормально.
exec "${setup_dir}/setup"
# cleanup by trap on error
