#!/bin/bash
# safe bash
set -o errexit -o noclobber -o nounset -o pipefail

# get config
readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
. "${root_dir}/load_config.bash"

"${setup_dir}/destroy_vms"
time "${setup_dir}/install" "$@"
time "${setup_dir}/setup"

exit 0
