#!/bin/bash
# safe bash
set -o errexit -o noclobber -o nounset -o pipefail

# get config
readonly setup_dir="$(dirname "${BASH_SOURCE[0]}")"

"${setup_dir}/destroy_vms"
time "${setup_dir}/install" "$@"
time "${setup_dir}/setup"

exit 0
