#!/bin/bash
# safe bash
set -o errexit -o noclobber -o nounset -o pipefail

# get config
readonly setup_dir="$(dirname "${BASH_SOURCE[0]}")"
. "${setup_dir}/load_config.bash"

if ! $autoVirtualBox
then
	echo 'Этот скрипт работает только со snapshot сделанными в VirtualBox.'
	exit 1
fi

. "${setup_dir}/rollback.bash"
rollback 'setup'
exit 0
