#!/bin/bash
# $@ номера кластеров, если пустой то все (включая Group0)
# safe bash
set -o errexit -o noclobber -o nounset -o pipefail

# get config
readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
. "${root_dir}/load_config.bash"

if ! $autoVirtualBox
then
	echo 'Этот скрипт работает только со snapshot сделанными в VirtualBox.'
	exit 1
fi

. "${lib_dir}/rollback.bash"
. "${lib_dir}/clusters2hosts.bash"

# $@ номера кластеров, если пустой то все (включая Group0)
readonly clusters="${*:-${!cluster_vms[*]}}"

rollback 'setup' $(clusters2hosts ${clusters})

exit 0
