#!/bin/bash
# Copyright Ⓒ 2020 "Sberbank Real Estate Center" Limited Liability Company.
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the Software
# is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

# safe bash
set -o errexit -o noclobber -o nounset -o pipefail -o xtrace

# get config
readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
. "${root_dir}/load_config.bash"

. "${lib_dir}/vm_ssh.bash"
. "${lib_dir}/tmux.bash"
. "${lib_dir}/cleanup.bash"
if $autoVirtualBox
then
	. "${lib_dir}/delete_snapshot.bash"
	. "${lib_dir}/rollback.bash"
fi

trap cleanup EXIT
if $autoVirtualBox
then
	rollback 'install'
	# Наличине скриншота setup будет маркером, что setup1 скрипт отработал нормально.
	delete_snapshot 'setup'
else
	echo 'При автоматической установке здесь происходит откат к snapshot, который был создан после установки пакетов.'
	echo 'Перед следующим этапом убедитесь, что у сетевого интерфейса, который будет использоваться с floating ip имя eth0.'
	read -p 'press enter'
fi

tmux_init
declare -i n=${#cluster_vms[@]} i=0
for c in ${!cluster_vms[@]}
do
	tmux respawn-pane -k "sleep $i && '${setup_dir}/setup1' ${c}"
	if [ $n -gt 1 ]
	then
		tmux split-window -v -p $((100-100/n))
		let n-=1
	fi
	let i+=1
done; unset c n i
tmux_attach
# Наличине скриншота setup будет маркером, что распараллелеиная настройка кластеров отработала нормально.
exit 0
# cleanup by trap
