#!/bin/bash
# safe bash
set -o errexit -o noclobber -o nounset -o pipefail -o xtrace

# get config
readonly root_dir="$(dirname "${BASH_SOURCE[0]}")/.."
. "${root_dir}/load_config.bash"

. "${lib_dir}/vm_ssh.bash"
. "${lib_dir}/tmux.bash"
if $autoVirtualBox
then
	. "${lib_dir}/delete_snapshot.bash"
	. "${lib_dir}/rollback.bash"
fi

if $autoVirtualBox
then
	rollback 'install'
	# Наличине скриншота setup будет маркером, что setup1 скрипт отработал нормально.
	delete_snapshot 'setup'
else
	echo 'При автоматической установке здесь происходит откат к snapshot, который был создан после установки пакетов.'
	echo 'Перед следующим этапом убедитесь, что у сетевого интерфейса, который будет использоваться с floating ip имя eth0.'
	read -p 'press enter'
fi

tmux_init
declare -i n=${#cluster_vms[@]} i=0
for c in ${!cluster_vms[@]}
do
	tmux respawn-pane -k "sleep $i && '${setup_dir}/setup1' ${c}"
	if [ $n -gt 1 ]
	then
		tmux split-window -v -p $((100-100/n))
		let n-=1
	fi
	let i+=1
done; unset c n i
tmux_attach

# Наличине скриншота setup будет маркером, что распараллелеиная настройка кластеров отработала нормально
exit 0
