# Copyright Ⓒ 2020 "Sberbank Real Estate Center" Limited Liability Company.
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the Software
# is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

# color chart
# https://upload.wikimedia.org/wikipedia/commons/9/95/Xterm_color_chart.png
# set root to red
root_cursor_color='#FF0000'
root_prompt_color='196'
# default colors
export CURSOR_COLOR='#EEEEEE'
export PROMPT_COLOR='255'
# local stuff (rewrite default colors there)
[[ -f ~/.bashrc_local ]] && . ~/.bashrc_local
#my favorite PS1
unset PS1
if [ "${TERM}" = 'linux' ]
then
	# uncolored
	PS1='\t j\j \u@\h:\w\n\$ '
else
	# colored
	PS1='\[\e[38;5;'"$PROMPT_COLOR"'m\]'
	PS1="$PS1"'\t j\j '
	[[ $UID == 0 ]] && { PS1="$PS1"'\[\e[38;5;'"$root_prompt_color"'m\]'; }
	PS1="$PS1"'\u'
	[[ $UID == 0 ]] && { PS1="$PS1"'\[\e[38;5;'"$PROMPT_COLOR"'m\]'; }
	PS1="$PS1"'@\h:\w\n'
	PS1="$PS1"'\[\e]12;'"$CURSOR_COLOR"'\a\]'
	if [[ $UID == 0 ]]; then
		PS1="$PS1"'\[\e[38;5;'"$root_prompt_color"'m\]'
	else
		PS1="$PS1"'\[\e[38;5;'"$PROMPT_COLOR"'m\]'
	fi
	PS1="$PS1"'\$ \[\e[m\]'
fi
complete -C '/usr/bin/aws_completer' aws
